# plan-tracker-init.py — Initialize plan-tracker Workspace
# Version: 1.0 | For agent-planner P2 plan-tracker initialization
# Creates workspace structure + sample tracker + CLI wrapper

import json
import os
import sys
from datetime import datetime

WORKSPACE_PLAN_TRACKER = os.path.join(
    os.path.expanduser("~"), ".qclaw", "workspace", "plan-tracker"
)
EVOLUTION_LOG = os.path.join(WORKSPACE_PLAN_TRACKER, "evolution-log.md")

def init_workspace():
    """Create plan-tracker directory and evolution log."""
    os.makedirs(WORKSPACE_PLAN_TRACKER, exist_ok=True)

    if not os.path.exists(EVOLUTION_LOG):
        with open(EVOLUTION_LOG, "w", encoding="utf-8") as f:
            f.write("""# Plan Tracker Evolution Log

> Auto-generated by plan-tracker-init.py
> Format: `- {date} | {plan-id} | {summary} | {status}`

---

""")
        print(f"[plan-tracker] Created evolution log: {EVOLUTION_LOG}")

def create_tracker(plan_id, plan_name, description="", owner="QClaw"):
    """Create a new plan tracker file."""
    tracker = {
        "trackerVersion": "1.0",
        "planId": plan_id,
        "planName": plan_name,
        "createdAt": datetime.now().isoformat(),
        "currentVersion": "v1",
        "status": "in_progress",
        "owner": owner,
        "description": description,
        "versions": [
            {
                "version": "v1",
                "createdAt": datetime.now().isoformat(),
                "createdBy": owner,
                "summary": "Initial version",
                "iteration": 1,
                "changes": []
            }
        ],
        "pendingChanges": [],
        "completedChanges": [],
        "nextReminder": None
    }

    filepath = os.path.join(WORKSPACE_PLAN_TRACKER, f"{plan_id}.json")
    if os.path.exists(filepath):
        print(f"[plan-tracker] Warning: {plan_id}.json already exists, appending version instead")
        return add_version(plan_id, f"Update from init")

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(tracker, f, indent=2, ensure_ascii=False)

    append_evolution(plan_id, plan_name, "Created tracker", "in_progress")
    print(f"[plan-tracker] Created: {filepath}")
    return tracker

def add_version(plan_id, summary, owner="QClaw"):
    """Append a new version to existing tracker."""
    filepath = os.path.join(WORKSPACE_PLAN_TRACKER, f"{plan_id}.json")
    if not os.path.exists(filepath):
        print(f"[plan-tracker] Error: {plan_id}.json not found")
        return None

    with open(filepath, "r", encoding="utf-8") as f:
        tracker = json.load(f)

    # Parse current version number
    current = tracker["currentVersion"]  # e.g. "v1"
    version_num = int(current[1:]) + 1
    new_version = f"v{version_num}"

    new_ver_block = {
        "version": new_version,
        "createdAt": datetime.now().isoformat(),
        "createdBy": owner,
        "summary": summary,
        "iteration": len(tracker["versions"]) + 1,
        "changes": []
    }

    tracker["versions"].append(new_ver_block)
    tracker["currentVersion"] = new_version

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(tracker, f, indent=2, ensure_ascii=False)

    append_evolution(plan_id, tracker["planName"], summary, "in_progress")
    print(f"[plan-tracker] Added version {new_version} to {plan_id}")
    return tracker

def add_change(plan_id, change_desc, change_type="other", target="", priority="P1", due_at=None):
    """Add a pending change to current version."""
    filepath = os.path.join(WORKSPACE_PLAN_TRACKER, f"{plan_id}.json")
    if not os.path.exists(filepath):
        print(f"[plan-tracker] Error: {plan_id}.json not found")
        return None

    with open(filepath, "r", encoding="utf-8") as f:
        tracker = json.load(f)

    current_ver = tracker["currentVersion"]
    version_block = None
    for v in tracker["versions"]:
        if v["version"] == current_ver:
            version_block = v
            break

    if not version_block:
        print(f"[plan-tracker] Error: version block not found for {current_ver}")
        return None

    # Generate change ID
    chg_id = f"chg-{len(version_block['changes']) + 1:03d}"

    change = {
        "id": chg_id,
        "description": change_desc,
        "type": change_type,
        "target": target,
        "priority": priority,
        "appliedAt": None,
        "status": "pending",
        "appliedBy": None,
        "reminderCronId": None,
        "dueAt": due_at,
        "notes": ""
    }

    version_block["changes"].append(change)
    tracker["pendingChanges"].append(chg_id)

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(tracker, f, indent=2, ensure_ascii=False)

    print(f"[plan-tracker] Added {chg_id} to {plan_id}: {change_desc}")
    return tracker

def mark_applied(plan_id, chg_id, applied_by="QClaw"):
    """Mark a change as applied."""
    filepath = os.path.join(WORKSPACE_PLAN_TRACKER, f"{plan_id}.json")
    with open(filepath, "r", encoding="utf-8") as f:
        tracker = json.load(f)

    for version in tracker["versions"]:
        for change in version["changes"]:
            if change["id"] == chg_id:
                change["status"] = "applied"
                change["appliedAt"] = datetime.now().isoformat()
                change["appliedBy"] = applied_by
                break

    tracker["pendingChanges"] = [c for c in tracker["pendingChanges"] if c != chg_id]
    tracker["completedChanges"].append(chg_id)

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(tracker, f, indent=2, ensure_ascii=False)

    print(f"[plan-tracker] Marked {chg_id} as applied in {plan_id}")

def list_trackers():
    """List all plan trackers."""
    if not os.path.exists(WORKSPACE_PLAN_TRACKER):
        return []
    return [f[:-5] for f in os.listdir(WORKSPACE_PLAN_TRACKER) if f.endswith(".json")]

def show_tracker(plan_id):
    """Display tracker summary."""
    filepath = os.path.join(WORKSPACE_PLAN_TRACKER, f"{plan_id}.json")
    if not os.path.exists(filepath):
        print(f"[plan-tracker] Not found: {plan_id}")
        return
    with open(filepath, "r", encoding="utf-8") as f:
        tracker = json.load(f)

    print(f"\n=== Plan Tracker: {tracker['planName']} ({tracker['planId']}) ===")
    print(f"Status: {tracker['status']} | Version: {tracker['currentVersion']} | Owner: {tracker['owner']}")
    print(f"Created: {tracker['createdAt'][:10]}")
    print(f"Pending: {len(tracker['pendingChanges'])} | Completed: {len(tracker['completedChanges'])}")
    for version in tracker["versions"]:
        print(f"\n  {version['version']}: {version['summary']} ({version['createdAt'][:10]})")
        for change in version["changes"]:
            print(f"    {change['id']}: [{change['status']}] {change['description'][:60]}")

def append_evolution(plan_id, plan_name, summary, status):
    """Append to evolution log."""
    entry = f"- {datetime.now().strftime('%Y-%m-%d')} | {plan_id} | {plan_name} | {summary} | {status}\n"
    with open(EVOLUTION_LOG, "a", encoding="utf-8") as f:
        f.write(entry)

def main():
    if len(sys.argv) < 2:
        print("""[plan-tracker] v1.0 — CLI

Usage:
  python plan-tracker-init.py init                           Initialize workspace
  python plan-tracker-init.py create <id> <name> [desc]     Create new tracker
  python plan-tracker-init.py add <id> <desc> [type]        Add pending change
  python plan-tracker-init.py apply <id> <chg-id>           Mark change applied
  python plan-tracker-init.py show <id>                     Show tracker
  python plan-tracker-init.py list                           List all trackers
  python plan-tracker-init.py version <id> <summary>         Add new version
""")
        sys.exit(0)

    cmd = sys.argv[1]

    if cmd == "init":
        init_workspace()
        print(f"[plan-tracker] Ready. Workspace: {WORKSPACE_PLAN_TRACKER}")

    elif cmd == "create":
        if len(sys.argv) < 4:
            print("[plan-tracker] Usage: create <plan-id> <plan-name> [description]")
            sys.exit(1)
        plan_id = sys.argv[2]
        plan_name = sys.argv[3]
        desc = sys.argv[4] if len(sys.argv) > 4 else ""
        create_tracker(plan_id, plan_name, desc)

    elif cmd == "add":
        if len(sys.argv) < 4:
            print("[plan-tracker] Usage: add <plan-id> <change-desc> [type]")
            sys.exit(1)
        plan_id = sys.argv[2]
        change_desc = sys.argv[3]
        change_type = sys.argv[4] if len(sys.argv) > 4 else "other"
        add_change(plan_id, change_desc, change_type)

    elif cmd == "apply":
        if len(sys.argv) < 4:
            print("[plan-tracker] Usage: apply <plan-id> <change-id>")
            sys.exit(1)
        plan_id = sys.argv[2]
        chg_id = sys.argv[3]
        mark_applied(plan_id, chg_id)

    elif cmd == "show":
        if len(sys.argv) < 3:
            print("[plan-tracker] Usage: show <plan-id>")
            sys.exit(1)
        show_tracker(sys.argv[2])

    elif cmd == "list":
        trackers = list_trackers()
        print(f"[plan-tracker] {len(trackers)} trackers:")
        for t in trackers:
            print(f"  - {t}")

    elif cmd == "version":
        if len(sys.argv) < 4:
            print("[plan-tracker] Usage: version <plan-id> <summary>")
            sys.exit(1)
        add_version(sys.argv[2], sys.argv[3])

if __name__ == "__main__":
    main()